### ISSUE TITLE
game don't start plz test the plugin

### ISSUE THREAD

**Issue by Astra-520** [ThatAquarel/HypixelBedwars1.8.9#1]
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin
game don't start plz test the plugin

**Comment by ThatAquarel** [comment]
Sorry about that. This plugin is still a work in progress and will not be done in sometime. Many key features are missing. If you would still like to test, you can run the /bwstart command to start the game and the /bwreset command to stop the game.
