### ISSUE TITLE
When can You add map setting mode to this plugin

### ISSUE THREAD

**Issue by Astra-520** [ThatAquarel/HypixelBedwars1.8.9#2]
When can You add map setting mode to this plugin

**Comment by Astra-520** [comment]
I'm looking forward to your plugin

**Comment by ThatAquarel** [comment]
I already have the most popular maps planned out, such as lighthouse, speedway, airshow, etc. They will need some time to get implemented with a map selector.

**Comment by Astra-520** [comment]
thanks
